import { StyleSheet } from "react-native";

export const stylesExpenseFormModal = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 20,
        borderRadius: 10,
    },
    title: {
        color: "#FFFFFF",
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 20,
        textAlign: "center",
    },
    fieldContainer: {
        marginBottom: 15,
    },
    label: {
        color: "#FFF",
        fontSize: 14,
        fontWeight: "bold",
        marginBottom: 5,
    },
    input: {
        backgroundColor: "#4c4b4b",
        color: "#FFF",
        borderRadius: 5,
        padding: 10,
        fontSize: 16,
    },
    picker: {
        backgroundColor: "#4c4b4b",
        color: "#FFF",
        borderRadius: 5,
        padding: 5,
        marginBottom: 10,
    },
    pickerButton: {
        backgroundColor: "#4c4b4b",
        padding: 12,
        borderRadius: 5,
        marginBottom: 15,
        justifyContent: "center",
    },
    pickerButtonText: {
        color: "#FFF",
        fontSize: 16,
    },
    dateTimeContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 15,
    },
    datePickerButton: {
        flex: 1,
        backgroundColor: "#444",
        padding: 12,
        borderRadius: 5,
        marginHorizontal: 5,
    },
    datePickerText: {
        color: "#FFF",
        textAlign: "center",
        fontWeight: "bold",
    },
    saveButton: {
        backgroundColor: "#317bcf",
        padding: 12,
        borderRadius: 5,
        marginBottom: 10,
        alignItems: "center",
    },
    cancelButton: {
        backgroundColor: "#E23C44",
        padding: 12,
        borderRadius: 5,
        alignItems: "center",
    },
    scrollView: {
        flexGrow: 1,
        justifyContent: "center",
    },
    buttonText: {
        color: "#FFF",
        fontWeight: "bold",
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.6)",
    },
    modalContent: {
        width: "80%",
        backgroundColor: "#ffffff",
        borderRadius: 10,
        padding: 20,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalOption: {
        width: "100%",
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: "#444",
        alignItems: "center",
    },
    modalOptionText: {
        fontSize: 16,
        color: "#000000",
    },
    modalCancelButton: {
        marginTop: 20,
        padding: 12,
        backgroundColor: "#E23C44",
        borderRadius: 5,
        alignItems: "center",
        width: "100%",
    },
    modalCancelButtonText: {
        fontSize: 16,
        color: "#FFF",
        fontWeight: "bold",
    },
});
