import { StyleSheet } from "react-native";

export const stylesFilterModal = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 20,
        borderRadius: 10,
    },
    title: {
        color: "#FFFFFF",
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 20,
        textAlign: "center",
    },
    picker: {
        backgroundColor: "#4c4b4b",
        color: "#FFF",
        borderRadius: 5,
        marginBottom: 15,
    },
    pickerButton: {
        backgroundColor: "#4c4b4b",
        padding: 12,
        borderRadius: 5,
        marginBottom: 15,
        justifyContent: "center",
    },
    pickerButtonText: {
        color: "#FFF",
        fontSize: 16,
    },
    applyButton: {
        backgroundColor: "#28A745",
        padding: 12,
        borderRadius: 5,
        marginBottom: 10,
        alignItems: "center",
    },
    applyButtonText: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 16,
    },
    cancelButton: {
        backgroundColor: "#DC3545",
        padding: 12,
        borderRadius: 5,
        alignItems: "center",
    },
    cancelButtonText: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 16,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.6)",
    },
    modalContent: {
        width: "80%",
        backgroundColor: "#ffffff",
        borderRadius: 10,
        padding: 20,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalOption: {
        width: "100%",
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: "#444",
        alignItems: "center",
    },
    modalOptionText: {
        fontSize: 16,
        color: "#000000",
    },
    modalCancelButton: {
        marginTop: 20,
        padding: 12,
        backgroundColor: "#E23C44",
        borderRadius: 5,
        alignItems: "center",
        width: "100%",
    },
    modalCancelButtonText: {
        fontSize: 16,
        color: "#FFF",
        fontWeight: "bold",
    },
});
