import { StyleSheet } from "react-native";

export const stylesSubCategoryFormModal = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 20,
    },
    title: {
        color: "#FFFFFF",
        fontSize: 20,
        fontWeight: "bold",
        marginBottom: 20,
        textAlign: "center",
    },
    fieldContainer: {
        marginBottom: 20,
        width: "100%",
    },
    label: {
        color: "#FFF",
        fontSize: 14,
        fontWeight: "bold",
        marginBottom: 5,
    },
    input: {
        backgroundColor: "#2D2D2D",
        color: "#FFF",
        borderRadius: 5,
        padding: 15,
        fontSize: 16,
        width: "100%",
    },
    textarea: {
        height: 120,
        textAlignVertical: "top",
    },
    charCounter: {
        color: "#A9A9A9",
        fontSize: 12,
        textAlign: "right",
        marginTop: 5,
    },
    pickerContainer: {
        backgroundColor: "#2D2D2D",
        borderRadius: 5,
        overflow: "hidden",
    },
    saveButton: {
        backgroundColor: "#317bcf",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 5,
        marginBottom: 10,
        width: "100%",
        alignItems: "center",
    },
    cancelButton: {
        backgroundColor: "#E23C44",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 5,
        width: "100%",
        alignItems: "center",
    },
    buttonText: {
        color: "#FFF",
        fontWeight: "bold",
        fontSize: 16,
    },
    picker: {
        color: "#FFF",
    },
    pickerButton: {
        backgroundColor: "#2D2D2D",
        padding: 12,
        borderRadius: 5,
        justifyContent: "center",
    },
    pickerButtonText: {
        color: "#FFF",
        fontSize: 16,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.6)",
    },
    modalContent: {
        width: "80%",
        backgroundColor: "#ffffff",
        borderRadius: 10,
        padding: 20,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalOption: {
        width: "100%",
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: "#444",
        alignItems: "center",
    },
    modalOptionText: {
        fontSize: 16,
        color: "#000000",
    },
    modalCancelButton: {
        marginTop: 20,
        padding: 12,
        backgroundColor: "#E23C44",
        borderRadius: 5,
        alignItems: "center",
        width: "100%",
    },
    modalCancelButtonText: {
        fontSize: 16,
        color: "#FFF",
        fontWeight: "bold",
    },
});
